---
title: "ngg2 manuscript summaries, tables, and figures"
author: "Elisha Roberson"
date: "`r Sys.Date()`"
output: html_document
---

```{r genericFxns, message=FALSE, echo=FALSE }
colorBlindPalette = c( "#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7" )

load_bioc_libraries = function( libName=NA )
{
  if ( !require( libName, character.only = TRUE ) ) {
		source( "http://www.bioconductor.org/biocLite.R" )
		biocLite( libName, character.only = TRUE, suppressUpdates=TRUE  )
		
		if ( !require( libName, character.only = TRUE ) )
		{
			stop( "Couldn't install", libName, "from Bioconductor. Please install manually." )
		}
	}
}

load_r_libraries = function( libName=NA )
  {
    if ( !require( libName, character.only = TRUE ) ) {
      install.packages( libName )
      if ( !require( libName, character.only = TRUE ) ) {
        stop( "Couldn't install", libName, "from R packages. Please install manually." )
      }
    }
  }
```

## Load needed libraries
```{r, loadLibs, message=FALSE}
load_r_libraries( "colorspace" )
load_r_libraries( "stringr" )
load_bioc_libraries( "plyr" )
load_bioc_libraries( "dplyr" )
load_bioc_libraries( "magrittr" )
load_bioc_libraries( "reshape2" )
load_bioc_libraries( "ggplot2" )
load_bioc_libraries( "xtable" )
load_bioc_libraries( "tidyr" )
```

```{r analysisFxns, message=FALSE, echo=FALSE }
species2Abbreviation = function( species_name )
  {
  split_vals = species_name %>% str_split( pattern=" " )
  first = split_vals[[1]][1] %>% str_sub( start=1, end=1 )
  second = split_vals[[1]][2] %>% str_sub( start=1, end=1 )
  
  return( paste( first, second, sep="" ) )
  }

strand2Matrix = function( filename )
  {
  inData = read.csv( filename, header=TRUE )
  rows = as.character( inData[,1] )
  
  header = scan( file=filename, 'character', 1, quiet=TRUE ) %>%
    str_split( ',' ) %>%
    unlist
  
  sense.ndx = which( header == "+" )
  antisense.ndx = which( header == "-" )
  
  inData = as.matrix( inData[,c(sense.ndx, antisense.ndx)] )
  colnames( inData ) = c( "Sense", "Antisense" )
  rownames( inData ) = rows
  
  return( inData )
  }

pam2Matrix = function( filename )
  {
  inData = read.csv( filename, header=TRUE )
  rownames( inData ) = as.character( inData[,1] )
  inData = as.matrix( inData[,-c(1)] )
  
  return( inData )
  }

prepForPAMplot = function( pamCountMatrix, nameChange=abbrevNames )
  {
  pam.fract = pamCountMatrix / rowSums( pamCountMatrix )
  
  rownames( pam.fract ) = nameChange[ rownames( pam.fract ) ]
  
  pam.fract = melt( pam.fract )
  colnames( pam.fract ) = c( "Species", "PAM", "Fraction" )
  
  return( pam.fract )
  }

prepForStrandPlot = function( strandCountMatrix, nameChange=abbrevNames )
  {
  strand.fract = strandCountMatrix / rowSums( strandCountMatrix )

  rownames( strand.fract ) = nameChange[ rownames( strand.fract ) ]
  
  strand.fract = melt( strand.fract )
  colnames( strand.fract ) = c( "Species", "Strand", "Fraction" )
  
  strand.fract$Fraction = round( strand.fract$Fraction, 3 )
  
  return( strand.fract )
  }

prepForPAMplot = function( pamCountMatrix, nameChange=abbrevNames )
  {
  pam.fract = pamCountMatrix / rowSums( pamCountMatrix )
  
  rownames( pam.fract ) = nameChange[ rownames( pam.fract ) ]
  
  pam.fract = melt( pam.fract )
  colnames( pam.fract ) = c( "Species", "PAM", "Fraction" )
  
  return( pam.fract )
  }

strandBinom = function( inFrame )
  {
  sense = which( inFrame$Var2 == "Sense" )
  antisense = which( inFrame$Var2 == "Antisense" )
  
  probs = binom.test( x=inFrame[sense,"value"], n=sum(inFrame[,"value"] ), p=0.5, alternative="two.sided" )
  
  return( c( "p.value" = probs$p.value, "estimate" = probs$estimate[[1]] ) )
  }

pamBinom = function( inFrame )
  {
  curr.species = as.character( unique( inFrame[,"Var1"] ) )
  gc = scan( paste( "gc_content/", curr.species, "_gcPerc.txt", sep="" ), n=1,  quiet=TRUE )
  
  agg = which( inFrame$Var2 == "AGG" )
  cgg = which( inFrame$Var2 == "CGG" )
  ggg = which( inFrame$Var2 == "GGG" )
  tgg = which( inFrame$Var2 == "TGG" )
  
  gcCount = sum( inFrame$value[c( cgg, ggg ) ] )
  total = sum( inFrame[,"value"] )
  
  probs = binom.test( x=gcCount, n=total, p=gc, alternative="two.sided" )
  
  return( c( "gc"=gc, "p.value" = probs$p.value, "estimate" = probs$estimate[[1]] ) )
  }

fractionCut = function( inputFrame )
  {
  cut = which( inputFrame$gRNAs == "Cut" )
  uncut = which( inputFrame$gRNAs == "Uncut" )
  
  total = sum( inputFrame[c(cut,uncut),"Freq"] )
  
  return( c(Fraction=inputFrame[cut,"Freq"] / total ) )
  }
```

## Setup species info and palette
```{r, species_stuff, message=FALSE}
species = scan( 'species', 'character', quiet=TRUE )

formalSpeciesNames = species %>%
  str_to_title %>%
  str_replace( "_", " " )

names( formalSpeciesNames ) = species

abbrevNames = llply( formalSpeciesNames, .fun=species2Abbreviation ) %>% unlist
```

## General stats and numbers

### Overall counts input and stats
```{r import, message=FALSE}
summary.counts = read.csv( "R_output/all_species_counts.csv" )

genomeSizes = summary.counts[,"MbGenome"]
names( genomeSizes ) = as.character( summary.counts$X )

species_order = names( genomeSizes )[ order( genomeSizes ) ]
formal_order = formalSpeciesNames[ species_order ] %>% unname

summary.counts = as.matrix( summary.counts[,-c(1,6)] )
rownames( summary.counts ) = species
summary.counts = summary.counts[species_order,]

total.all.gRNAs = colSums( summary.counts )

summary.counts.perMb = summary.counts / genomeSizes[ rownames( summary.counts ) ]
```

### Count by species table
```{r countBySpeciesTable, echo=FALSE, message=FALSE, results='asis'}
rownames( summary.counts ) = formalSpeciesNames[ rownames( summary.counts ) ]

print( xtable( rbind( summary.counts, total.all.gRNAs ), digits=c(0,0,0,0,0), display=c('s', 'd', 'd', 'd', 'd')), type='html' )
```

### Counts / mb
```{r CountsPerMbBySpeciesTable,message=FALSE, echo=FALSE, results='asis'}
rownames( summary.counts.perMb ) = formalSpeciesNames[ rownames( summary.counts.perMb ) ]

print( xtable( summary.counts.perMb, digits=c(0,2,2,2,2), display=c('s', 'f', 'f', 'f', 'f')), type='html' )
```

```{r statsCntPerMb, message=FALSE}
summary( summary.counts.perMb )
```

## Strandedness

### Slurp
```{r readstrand, message=FALSE}
all.strand = strand2Matrix( "R_output/all_species_strand.csv" )

gstart.strand = strand2Matrix( "R_output/all_species_gstart_strand.csv" )
```

### Table of binomial probs
```{r strandBinom, message=FALSE, results='asis' }
all.strand.pval = all.strand %>%
  melt %>%
  ddply( .variables="Var1", .fun=strandBinom ) %>%
  cbind( gRNA_Type="All", . )

gstart.strand.pval = gstart.strand %>%
  melt %>%
  ddply( .variables="Var1", .fun=strandBinom ) %>%
  cbind( gRNA_Type="Canonical", . )

strand.pvals = rbind( all.strand.pval, gstart.strand.pval )

colnames( strand.pvals )[2] = "Species"
strand.pvals$Species = formalSpeciesNames[ as.character( strand.pvals$Species ) ]

strand.pvals = cbind( strand.pvals, "p.adj" = p.adjust( strand.pvals$p.value ) )

strand.pvals = strand.pvals[, c("gRNA_Type", "Species", "estimate", "p.value", "p.adj" )]

strand.pvals = strand.pvals %>%
  mutate( estimate = round( estimate, 3 ) )

print( xtable( strand.pvals, digits=c(0,0,0,3,2,2), display=c('s', 's', 's', 'f','E', 'E')), type='html', include.rownames=FALSE  )
```

## PAM sites

### Plot
```{r allPamfigure, message=FALSE, fig.path="figures/", fig.keep='all', dpi=300}
all.pam.forplot = pam2Matrix( "R_output/all_species_pam.csv" ) %>%
  prepForPAMplot %>%
  cbind( SiteType="All", . )

gstart.pam.forplot = pam2Matrix( "R_output/all_species_gstart_pam.csv" ) %>%
  prepForPAMplot %>%
  cbind( SiteType="Canonical", . )

pam.forplot = rbind( all.pam.forplot, gstart.pam.forplot )

pam.plot = ggplot( pam.forplot, aes( x=Species, y=Fraction, fill=PAM ) ) +
  geom_bar( stat="identity" ) +
  facet_grid( .~SiteType ) +
  scale_fill_manual( values=colorBlindPalette ) +
  theme_bw() +
  theme( panel.grid.major.x = element_blank(), panel.grid.major.y = element_blank() )

pam.plot
```

### Binom probs
```{r, message=FALSE, results='asis'}
all.pam.pval = "R_output/all_species_pam.csv" %>%
  pam2Matrix %>%
  melt %>%
  ddply( .variables="Var1", .fun=pamBinom ) %>%
  cbind( "gRNA_Type"="All", . )

pam.pvals = "R_output/all_species_gstart_pam.csv" %>%
  pam2Matrix %>%
  melt %>%
  ddply( .variables="Var1", .fun=pamBinom ) %>%
  cbind( "gRNA_Type"="Canonical" ) %>%
  rbind( all.pam.pval, . )

pam.pvals = cbind( pam.pvals, p.adj = p.adjust( pam.pvals$p.value ) )

colnames( pam.pvals )[2] = "Species"
pam.pvals$Species = formalSpeciesNames[ as.character( pam.pvals$Species ) ]

pam.pvals = pam.pvals %>%
  select( gRNA_Type, Species, gc, estimate, p.value, p.adj ) %>%
  mutate( gc = round( gc, 3 ) ) %>%
  mutate( estimate = round( estimate, 3 ) ) %>%
  mutate( p.value = signif( p.value, 2 ) ) %>%
  mutate( p.adj = signif( p.adj, 2 ) )

print( xtable( pam.pvals, digits=c(0,0,0,3,3,2,2), display=c('s','s', 's', 'f', 'f', 'E', 'E')), type='html', include.rownames=FALSE  )
```

## Gene cut rates

### Slurp
```{r getBiotypes, message=FALSE}
getList = c( "All gRNA"="R_output/all_species_all_gRNA_biotypes.csv", "All gRNA - Unique sites"="R_output/all_species_unique_gRNA_biotypes.csv", "Canonical gRNA"="R_output/all_species_gstart_gRNA_biotypes.csv", "Canonical gRNA - Unique sites"="R_output/all_species_gstart_unique_gRNA_biotypes.csv")

biotypes = ldply( getList, .fun=read.csv, header=TRUE ) %>%
  mutate( species = as.character( abbrevNames[species]) ) %>%
  mutate( species = factor( species, levels=abbrevNames[species_order] ) )

colnames( biotypes )[1] = "gRNA_Type"
colnames( biotypes )[2] = "Species"
```

### Table protein coding all cutters
```{r proteinAllTypes, message=FALSE, results='asis'}
biotypes.protein = subset( biotypes, gene_biotype == "protein_coding" ) %>%
  ddply( .variables = c("gRNA_Type", "Species"), .fun=fractionCut ) %>%
  spread( gRNA_Type, Fraction )

print( xtable( biotypes.protein, digits=c(0,0,3,3,3,3), display=c('s', 's', 'f', 'f', 'f', 'f')), type='html', include.rownames=FALSE  )
```

### table all types cut rate
```{r allBiotypeGstartUniqueTable, message=FALSE, results='asis'}
biotype.gstart.unique.table = subset( biotypes, gRNA_Type == "Canonical gRNA - Unique sites" ) %>%
  ddply( .variables=c("gRNA_Type", "Species", "gene_biotype" ), .fun=fractionCut ) %>%
  select( -gRNA_Type )

print( xtable( biotype.gstart.unique.table, digits=c(0,0,0,3), display=c('s', 's', 's','f')), type='html', include.rownames=FALSE  )
```

## Speed Benchmark

```{r benchmanrk, message=FALSE, results='asis'}
num_ngg2_cpu = scan( 'num_ngg2_cpus', 1, quiet=TRUE ) %>% as.integer

cpumode = c( '1cpu', 'multicpu' )
scantype = c( 'block', 'full' )

tab = data.frame()

for( sp.index in 1:length( species_order ) ) {
  this_species = species_order[sp.index]
  for( cpu.index in 1:length( cpumode ) ) {
    this_cpu = cpumode[cpu.index]
    
    if ( this_cpu == '1cpu' ){
      cpu_num = 1
    } else {
      cpu_num = num_ngg2_cpu
    }
    
    for (scan.index in 1:length( scantype ) ) {
      this_scan = scantype[scan.index]
      
      curr_file = paste( "benchmark/", this_species, "_benchmark_", this_scan, "_", this_cpu, "_grnas.log", sep="" )
      
      curr_time = scan( curr_file, 'character', 1, quiet=TRUE ) %>%
        as.numeric
      
      if ( sum( dim( tab ) ) == 0 ) {
        tab = data.frame( Species=this_species, CPUs=cpu_num, ScanType=this_scan, Time=curr_time )
      } else {
        tab = rbind( tab, data.frame( Species=this_species, CPUs=cpu_num, ScanType=this_scan, Time=curr_time ) )
      }
    }
  }
}

tab = tab %>%
  mutate( Class = paste( ScanType, "_", CPUs, "cpu", sep="" ) ) %>%
  select( Species, Class, Time ) %>%
  mutate( Class = as.character( Class ) ) %>%
  mutate( Class = factor( Class, levels=c( "block_1cpu", "block_10cpu", "full_1cpu", "full_10cpu"))) %>%
  mutate( Species = as.character( Species ) ) %>%
  mutate( Species = factor( Species, levels=species_order ) ) %>%
  spread( Class, Time ) %>%
  mutate( Species = as.character( Species ) ) %>%
  mutate( Species = formalSpeciesNames[Species] )

bench.mat = tab[,-c(1)]
rownames( bench.mat ) = as.character( tab$Species )

print( xtable( bench.mat, digits=c(0,2,2,2,2), display=c('s', 'f', 'f','f', 'f')), type='html' )
```

## SessionInfo
```{r session, message=FALSE}
sessionInfo()
```
